package rules

import domain.*;
import java.util.Date;
import java.util.Collection;

rule "Cancelled bookings"
	when
		customer : Customer();
		numberOfBookings : Long(intValue > 3);
		ratioOfCancelledBookings : Double(doubleValue >= 0.5);
	then
		customer.getCustomerType().add("sospechoso");
		
end



rule "Inactive user"
	when
		$d : Date();
		$customer : Customer (createdAt < $d);
		
	then
		$customer.getCustomerType().add("veterano");
			
end